maio/urls.py
'''
File: urls.py

Module: ``maio.urls``

Maio URL Configuration.
'''

from __future__ import annotations
from typing import Any

from django.urls import path, include
from django.contrib.auth.decorators import login_required

from maio import views
from maio.views import ajax
from maio.admin import admin_site


urlpatterns: list[Any] = [
    # Admin
    path('maio_admin/', include('maioadmin.urls', namespace='maio_admin')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('password/', login_required(views.PasswordChangeView.as_view()), name='password'),
    path('password_change_done/', login_required(views.PasswordChangeDoneView.as_view()), name='password_change_done'),
    path('admin/', admin_site.urls),

    # Maio Views
    path('dashboard/', login_required(views.dashboard), name='dashboard'),
    path('logout/', login_required(views.logout), name='logout'),
    path('upload_media/', login_required(views.UploadMediaView.as_view()), name='upload_media'),
    path('edit_profile/', login_required(views.edit_profile), name='edit_profile'),
    path('search/', login_required(views.search), name='search'),
    path('library_share/<str:username>/', login_required(views.library_share), name='library_share'),
    path('library_share/', login_required(views.library_share), name='library_share'),

    # AJAX
    path('ajax/delete_media/', login_required(ajax.delete_media), name='delete_media'),
    path('ajax/change_thumbnail/', login_required(ajax.change_thumbnail), name='change_thumbnail'),
    path('ajax/rating/', login_required(ajax.rating), name='rating'),
    path('', views.home, name='home'),
]

maio/models/Bookmark.py
'''
File: Bookmark.py

Module: ``maio.models.Bookmark``
'''

from __future__ import annotations

import uuid

from django.db.models import Model, UUIDField, DateTimeField, ForeignKey, CASCADE
from django.db.models.base import ModelBase


class BookmarkMeta(ModelBase):
    '''Metaclass for Bookmark model.'''
    class Meta:
        verbose_name = 'Bookmark'
        verbose_name_plural = 'Bookmarks'
        app_label = 'maio'
        db_table_comment = 'Contains the Bookmarks for Media.'
        get_latest_by = ['-date_modified']
        # order_with_respect_to = ['user', 'date_added']
        ordering = ['-date_modified']
        # indexes = [
        #     Index(fields=('sort', 'name', 'is_default', 'date_added', '-date_modified'))
        # ]


class Bookmark(Model, metaclass=BookmarkMeta):
    '''Bookmark model.'''
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = ForeignKey(to='MaioUser', on_delete=CASCADE)
    media = ForeignKey(to='Media', on_delete=CASCADE)
    date_added = DateTimeField(auto_now_add=True)
    date_modified = DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} Bookmarks {self.media}"

maio/models/Caption.py
'''
File: Caption.py

Module: ``maio.models.Caption``
'''

from __future__ import annotations

import uuid

from django.db.models import (
    Model, UUIDField, ForeignKey, CharField, URLField, DateTimeField, TextField,
    CASCADE, DO_NOTHING,
)
from django.db.models.base import ModelBase

from .Media import Media
from .MaioMapType import MaioMapType
from django.utils.translation import gettext_lazy as _T


class CaptionMeta(ModelBase):
    '''Metaclass for Caption model.'''
    class Meta:
        verbose_name = 'Caption'
        verbose_name_plural = 'Captions'
        app_label = 'maio'
        db_table_comment = 'Captions are attached to Media.'
        get_latest_by = ['media', '-caption_date']
        # order_with_respect_to = ['media', 'caption_date']
        ordering = ['-caption_date']
        # indexes = [
        #     Index(fields=('sort', 'name', 'is_default', 'date_added', '-date_modified'))
        # ]

class Caption(Model, metaclass=CaptionMeta):
    '''Caption model.'''
    id = UUIDField(_T('UUID'), primary_key=True, default=uuid.uuid4, editable=False)
    media = ForeignKey(Media, on_delete=CASCADE)
    author = CharField(_T('Author'), max_length=1024, null=True, blank=True)
    url = URLField(_T('URL'), max_length=1024, null=True, blank=True)
    date_added = DateTimeField(_T('Date Added'), auto_now_add=True)
    date_modified = DateTimeField(_T('Date Modified'), auto_now=True)
    caption_date = DateTimeField(_T('Caption Date'), null=True, blank=True)
    caption_type = ForeignKey(to=MaioMapType, on_delete=DO_NOTHING, default=MaioMapType.default) # type: ignore
    caption = TextField(_T('Caption'))
    date_added = DateTimeField('Date Added', auto_now_add=True)
    date_modified = DateTimeField('Date Modified', auto_now_add=True)

    def __str__(self):
        return f"{self.media.name} - {self.caption_date} - {self.caption[0:20]}"

maio/models/Category.py
'''
File: Category.py

Module: ``maio.models.Category``
'''

from __future__ import annotations

import uuid

from django.db.models import (
    Model, UUIDField, CharField, DateTimeField, IntegerField, BooleanField,
    ForeignKey, Index,
    CASCADE,
)
from django.db.models.base import ModelBase


class CategoryMeta(ModelBase):
    '''Metaclass for Category model.'''
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        app_label = 'maio'
        db_table_comment = 'Categories are ways to group Media.'
        get_latest_by = ['-date_modified']
        # order_with_respect_to = ['']
        ordering = ['-date_modified']
        indexes = [
            Index(fields=('sort', 'name', 'is_default', 'date_added', '-date_modified'))
        ]


class Category(Model, metaclass=CategoryMeta):
    '''File model. Represents a file stored in filestore/media.'''

    #: UUID unique ID
    id = UUIDField('UUID', primary_key=True, default=uuid.uuid4, editable=False)

    #: Maio User
    user = ForeignKey(to='MaioUser', on_delete=CASCADE)

    #: Sort order
    sort = IntegerField('Sort Order (0-9)', default=0)

    #: Is Default?
    is_default = BooleanField('Is Default?', default=False)

    #: Name
    name = CharField('Category', max_length=1024, default='Default Category')

    #: Date added
    date_added = DateTimeField(auto_now_add=True)

    #: Date modified
    date_modified = DateTimeField(auto_now=True)

    def __str__(self) -> str:
        id = str(self.id)[0:6]
        return f"[{id}] (Sort: {self.sort}) {self.name}"

maio/models/Converted.py
'''
File: Converted.py

Module: ``maio.models.Converted``
'''

from __future__ import annotations

import uuid

from django.conf import settings
from django.db.models import (
    Model, UUIDField, ForeignKey, DateTimeField, PositiveIntegerField, DecimalField, FileField,
    CASCADE, DO_NOTHING,
)
from django.db.models.base import ModelBase
from django.utils.translation import gettext_lazy as _T

from conf import MaioConf


maio_conf = MaioConf(config=settings.MAIO_SETTINGS)

class ConvertedMeta(ModelBase):
    '''Metaclass for Converted model.'''
    class Meta:
        verbose_name = 'Converted File'
        verbose_name_plural = 'Converted Files'
        app_label = 'maio'
        db_table_comment = 'Converted Files.'
        get_latest_by = ['-date_modified']
        # order_with_respect_to = ['user', '-date_modified']
        ordering = ['-date_modified']
        # indexes = [
        #     Index(fields=('sort', 'name', 'is_default', 'date_added', '-date_modified'))
        # ]


class Converted(Model, metaclass=ConvertedMeta):
    '''Converteds model.'''
    id = UUIDField(_T('UUID'), primary_key=True, default=uuid.uuid4, editable=False)
    file = ForeignKey(to='File', on_delete=CASCADE)
    mime_type = ForeignKey(to='MaioMimeType', on_delete=DO_NOTHING)
    content_file = FileField(_T('Content File'), max_length=1024, upload_to=maio_conf.get_chain('converted', 'directory'))
    size = PositiveIntegerField(_T('Size (Bytes)'))
    width = PositiveIntegerField(_T('Width (Pixels)'))
    height = PositiveIntegerField(_T('Height (Pixels)'))
    length = DecimalField('Length (seconds)', max_digits=22, decimal_places=15)
    date_added = DateTimeField(_T('Date Added'), auto_now_add=True, editable=False)
    date_modified = DateTimeField(_T('Date Modified'), auto_now=True, editable=False)

    def __str__(self) -> str:
        return f"[{str(self.id)[0:6]}] - ({self.file}) - {self.mime_type}" # type: ignore

maio/models/FileStat.py
'''
File: FileStat.py

Module: ``maio.models.FileStat``
'''

from __future__ import annotations


from django.db.models import (
    Model, DateTimeField, PositiveBigIntegerField, BigAutoField,
)
from django.db.models.base import ModelBase
from django.utils.translation import gettext_lazy as _T

from maio.lib import sizeof_fmt


class FileStatMeta(ModelBase):
    '''Metaclass for FileStat model.'''
    class Meta:
        verbose_name = 'File Stat'
        verbose_name_plural = 'File Stats'
        app_label = 'maio'
        db_table_comment = 'Contains the number of files and their sizes of the current file store.'
        get_latest_by = ['-date_modified']
        # order_with_respect_to = ['user', 'date_added']
        ordering = ['-date_modified']
        # indexes = [
        #     Index(fields=('sort', 'name', 'is_default', 'date_added', '-date_modified'))
        # ]


class FileStat(Model, metaclass=FileStatMeta):
    '''Log model.'''
    id = BigAutoField(_T('ID'), primary_key=True)
    num_images = PositiveBigIntegerField(_T('Number of Images'), editable=False)
    images_bytes = PositiveBigIntegerField(_T('Number of Bytes of Images'), editable=False)
    num_audio = PositiveBigIntegerField(_T('Number of Audio Files'), editable=False)
    audio_bytes = PositiveBigIntegerField(_T('Number of Bytes of Audio'), editable=False)
    num_audio_converted = PositiveBigIntegerField(_T('Number of Converted Audio Files'), editable=False)
    audio_converted_bytes = PositiveBigIntegerField(_T('Number of Bytes of Converted Audio Files'), editable=False)
    num_videos = PositiveBigIntegerField(_T('Number of Videos'), editable=False)
    videos_bytes = PositiveBigIntegerField(_T('Number of Bytes of Video'), editable=False)
    num_videos_converted = PositiveBigIntegerField(_T('Number of Converted Videos'), editable=False)
    videos_converted_bytes = PositiveBigIntegerField(_T('Number of Bytes of Converted Videos'), editable=False)
    num_documents = PositiveBigIntegerField(_T('Number of Documents'), editable=False)
    documents_bytes = PositiveBigIntegerField(_T('Number of Bytes of Documents'), editable=False)
    num_others = PositiveBigIntegerField(_T('Number of Other Files'), editable=False)
    others_bytes = PositiveBigIntegerField(_T('Number of Bytes of Other Files'), editable=False)
    date_added = DateTimeField(_T('Date Added'), auto_now_add=True)
    date_modified = DateTimeField(_T('Date Modified'), auto_now=True)

    def __str__(self) -> str:
        return (
            f"[{self.id}] - ({self.date_modified}) "
            f"Images: {self.num_images}; "
            f"Audio: {self.num_audio}; "
            f"Videos: {self.num_videos}; "
            f"Documents: {self.num_documents}; "
            f"Others: {self.num_others}"
        )

    def get_file_sizes_human(self) -> tuple[str, str, str, str, str, str, str]:
        '''Get the images size in human readable units.'''
        return (
            sizeof_fmt(self.images_bytes),
            sizeof_fmt(self.audio_bytes),
            sizeof_fmt(self.audio_converted_bytes),
            sizeof_fmt(self.videos_bytes),
            sizeof_fmt(self.videos_converted_bytes),
            sizeof_fmt(self.documents_bytes),
            sizeof_fmt(self.others_bytes),
        )

    @staticmethod
    def save_stats(
        num_images: int,
        images_bytes: int,
        num_audio: int,
        audio_bytes: int,
        num_audio_converted: int,
        audio_converted_bytes: int,
        num_videos: int,
        videos_bytes: int,
        num_videos_converted: int,
        videos_converted_bytes: int,
        num_documents: int,
        documents_bytes: int,
        num_others: int,
        others_bytes: int,
    ) -> FileStat:
        '''Save current File Stats.'''
        try:
            file_stat = FileStat.objects.get(
                num_images=num_images,
                images_bytes=images_bytes,
                num_audio=num_audio,
                audio_bytes=audio_bytes,
                num_audio_converted=num_audio_converted,
                audio_converted_bytes=audio_converted_bytes,
                num_videos=num_videos,
                videos_bytes=videos_bytes,
                num_videos_converted=num_videos_converted,
                videos_converted_bytes=videos_converted_bytes,
                num_documents=num_documents,
                documents_bytes=documents_bytes,
                num_others=num_others,
                others_bytes=others_bytes,
            )
        except FileStat.DoesNotExist:
            file_stat = FileStat(
                num_images=num_images,
                images_bytes=images_bytes,
                num_audio=num_audio,
                audio_bytes=audio_bytes,
                num_audio_converted=num_audio_converted,
                audio_converted_bytes=audio_converted_bytes,
                num_videos=num_videos,
                videos_bytes=videos_bytes,
                num_videos_converted=num_videos_converted,
                videos_converted_bytes=videos_converted_bytes,
                num_documents=num_documents,
                documents_bytes=documents_bytes,
                num_others=num_others,
                others_bytes=others_bytes,
            )
        file_stat.save()
        return file_stat

maio/models/LibraryShare.py
'''
File: LibraryShare.py

Module: ``maio.models.LibraryShare``
'''

from __future__ import annotations

import uuid

from django.db.models import (
    Model, UUIDField, ForeignKey, DateTimeField, CharField,
    CASCADE,
)
from django.db.models.base import ModelBase
from django.utils.translation import gettext_lazy as _T

from .MaioUser import MaioUser
from .choices import PermissionChoices


class LibraryShareMeta(ModelBase):
    '''Metaclass for LibraryShare model.'''
    class Meta:
        verbose_name = 'Library Share'
        verbose_name_plural = 'Library Shares'
        app_label = 'maio'
        db_table_comment = 'Library sharing between two Maio Users.'
        get_latest_by = ['-date_modified']
        # order_with_respect_to = ['user', '-date_modified']
        ordering = ['-date_modified']
        # indexes = [
        #     Index(fields=('sort', 'name', 'is_default', 'date_added', '-date_modified'))
        # ]
        unique_together = ('from_user', 'to_user')


class LibraryShare(Model, metaclass=LibraryShareMeta):
    '''LibraryShare model.'''
    id = UUIDField(_T('UUID'), primary_key=True, default=uuid.uuid4, editable=False)
    from_user = ForeignKey(verbose_name=_T('From Maio User'), to=MaioUser, on_delete=CASCADE, related_name='from_user')
    to_user = ForeignKey(verbose_name=_T('To Maio User'), to=MaioUser, on_delete=CASCADE, related_name='to_user')
    permission = CharField(_T('Permissions'), default='denied', choices=PermissionChoices.choices)
    date_added = DateTimeField(_T('Date Added'), auto_now_add=True, editable=False)
    date_modified = DateTimeField(_T('Date Modified'), auto_now=True, editable=False)

    def __str__(self) -> str:
        return f"[{str(self.id)[0:6]}] ({self.permission}) From: {self.from_user} - To: {self.to_user}" # type: ignore

maio/models/Like.py
'''
File: Like.py

Module: ``maio.models.Like``
'''

from __future__ import annotations

import uuid

from django.db.models import Model, UUIDField, DateTimeField, ForeignKey, CASCADE
from django.db.models.base import ModelBase


class LikeMeta(ModelBase):
    '''Metaclass for Like model.'''
    class Meta:
        verbose_name = 'Like'
        verbose_name_plural = 'Likes'
        app_label = 'maio'
        db_table_comment = 'Contains the Likes for Media.'
        get_latest_by = ['-date_modified']
        # order_with_respect_to = ['user', 'date_added']
        ordering = ['-date_modified']
        # indexes = [
        #     Index(fields=('sort', 'name', 'is_default', 'date_added', '-date_modified'))
        # ]


class Like(Model, metaclass=LikeMeta):
    '''Like model.'''
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = ForeignKey(to='MaioUser', on_delete=CASCADE)
    media = ForeignKey(to='Media', on_delete=CASCADE)
    date_added = DateTimeField(auto_now_add=True)
    date_modified = DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} Likes {self.media}"

maio/models/Love.py
'''
File: Love.py

Module: ``maio.models.Love``
'''

from __future__ import annotations

import uuid

from django.db.models import Model, UUIDField, DateTimeField, ForeignKey, CASCADE
from django.db.models.base import ModelBase


class LoveMeta(ModelBase):
    '''Metaclass for Love model.'''
    class Meta:
        verbose_name = 'Love'
        verbose_name_plural = 'Loves'
        app_label = 'maio'
        db_table_comment = 'Contains the Loves for Media.'
        get_latest_by = ['-date_modified']
        # order_with_respect_to = ['user', 'date_added']
        ordering = ['-date_modified']
        # indexes = [
        #     Index(fields=('sort', 'name', 'is_default', 'date_added', '-date_modified'))
        # ]


class Love(Model, metaclass=LoveMeta):
    '''Love model.'''
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = ForeignKey(to='MaioUser', on_delete=CASCADE)
    media = ForeignKey(to='Media', on_delete=CASCADE)
    date_added = DateTimeField(auto_now_add=True)
    date_modified = DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.media.owner} loves {self.media}"

maio/templates/base/base.html
{% load static %}<!doctype html>
<html lang="en" class="maio maio-theme-default">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Maio: Media All In One">
    <meta name="author" content="Jonathan Sawyer <https://github.com/jonmsawyer/maio">
    <meta name="keywords" content="maio, media, all, in, one, all-in-one, file, media, images,
                                   pictures, video, songs, audio, clips, movies, documents, text">

    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"> <!-- IE -->
    <link rel="apple-touch-icon" type="image/png" href="{% static 'icons/favicon.png' %}"> <!-- iPhone -->
    <link rel="apple-touch-icon" type="image/png" sizes="72x72" href="{% static 'icons/favicon.png' %}"> <!-- iPad -->
    <link rel="apple-touch-icon" type="image/png" sizes="52x52" href="{% static 'icons/favicon.png' %}"> <!-- iPad -->
    <link rel="apple-touch-icon" type="image/png" sizes="114x114" href="{% static 'icons/favicon.png' %}"> <!-- iPhone4 -->
    <link rel="icon" type="image/png" href="{% static 'icons/favicon.png' %}"> <!-- Modern Browsers -->

    <title>{% block title %}Maio{% endblock title %} | Maio</title>

    <!-- Core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
          rel="stylesheet">
    <link href="{% static 'maio/css/core.css' %}" rel="stylesheet">

    <!-- Core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <script src="{% static 'maio/js/core.js' %}"></script>

    <!-- Template Styles and Scripts -->
    {% block stylesheets %}{% endblock stylesheets %}
    {% block style %}{% endblock style %}
    {% block scripts %}{% endblock scripts %}
  </head>

  <body>
    {% include 'base/nav.html' %}
    {% include 'base/error_panel.html' %}
    {% include 'base/info_panel.html' %}
    <main role="main" class="mt-5">
      {% block content %}{% endblock content %}
    </main>
    {% include 'base/footer.html' %}
    {% include 'base/debug.html' %}
  </body>
  {% block script %}{% endblock script %}
</html>

maio/templates/base/debug.html
{# Maio Debug #}

{% load static %}
{% load maio_extras %}

{% if request.user.is_superuser and user_setting.display_debug %}
<div class="container maio-debug">
  <hr>
  <h4>Debug</h4>
  <pre>User: {{ request.user }}
Query Dict: {{ query_dict.dict }}
Querystring: {{ query_dict.urlencode }}
Maio Theme: {{ user_setting.maio_theme }}
Default Dashboard View: {{ user_setting.default_dashboard_view }}
Default Dashboard Sort: {{ user_setting.default_dashboard_sort }}
Default Upload Media View: {{ user_setting.default_upload_media_view }}
Auto Upload Media: {{ user_setting.auto_upload_media }}
Redirect to Previous Page: {{ user_setting.redirect_to_previous_page_after_setting_save }}
Previous Page: {{ user_setting.previous_page }}</pre>
</div>
{% endif %}

maio/templates/base/error_panel.html
{# Maio Debug #}

{% load static %}
{% load maio_extras %}

<div class="maio-error-panel">
    <div id="error-panel" class="alert alert-danger maio-error-panel">
        <button type="button" class="btn-close" onclick="Maio.close_error_panel();" style="float: right;" aria-label="Close"></button>
        <h4 class="alert-heading">Error</h4>
        <div id="error"></div>
    </div>
</div>

maio/templates/base/footer.html
    <footer class="container">
      <hr>
      <p>&copy; Maio {% now 'Y' %}</p>
    </footer>

maio/templates/base/heading.html
{% load static %}
<h1 class="display-1" style="margin-top: 0em;">Maio</h1>
<h5 class="display-5">
    <span>Media</span> &nbsp; <span style="white-space: nowrap;">All In One<span>
</h5>

maio/templates/base/info_panel.html
{# Maio Debug #}

{% load static %}
{% load maio_extras %}

<div class="maio-info-panel">
    <div id="info-panel" class="alert alert-info maio-info-panel">
        <button type="button" class="btn-close" onclick="Maio.close_info_panel();" style="float: right;" aria-label="Close"></button>
        <h4 class="alert-heading">Info</h4>
        <div id="info"></div>
    </div>
</div>

maio/templates/base/login.html
{% if not request.user.is_authenticated %}
  <form method="post" style="text-align: center;">
    {% csrf_token %}
    <div style="border: 1px solid #212529;
                margin: 0 auto;
                padding: 20px;
                border-radius: 10px;">
        <h3>Maio Login</h3>
        <div class="input-group maio-input-group">
          <div class="input-group-prepend">
            <label class="input-group-text"
                    id="input-group-username"
                    for="{{ form.username.id_for_label }}"
            >{{ form.username.label }}</label>
          </div>
          <input type="text"
                  class="form-control"
                  aria-label="{{ form.username.label }}"
                  aria-describedby="inputGroup-sizing-sm"
                  name="{{ form.username.name }}"
                  id="{{ form.username.id_for_label }}">
        </div>
        <div class="input-group maio-input-group" style="margin-top: 10px;">
          <div class="input-group-prepend">
            <label class="input-group-text"
                    id="input-group-password"
                    for="{{ form.password.id_for_label }}"
            >{{ form.password.label }}</label>
          </div>
          <input type="password"
                  class="form-control"
                  aria-label="{{ form.password.label }}"
                  aria-describedby="inputGroup-sizing-sm"
                  name="{{ form.password.name }}"
                  id="{{ form.password.id_for_label }}">
        </div>
        <div style="margin-top: 10px">
            <button type="submit" class="btn btn-primary btn-lg">Log In</button>
        </div>
    </div>
  </form>
{% else %}
  <div style="text-align: center; float: right;">
      <div style="width: 600px;
                  border: 1px solid #212529;
                  margin: 0 auto;
                  padding: 20px;
                  border-radius: 10px;">
          <h3>Maio Dashboard</h3>
          <a class="btn btn-primary btn-lg" href="{% url 'dashboard' %}"
          >Go to the Maio Dashboard</a>
      </div>
  </div>
{% endif %}

maio/templates/base/logo.html
{% load static %}
<img src="{% static 'icons/maio_256.png' %}" class="front-page maio-logo">

maio/templates/base/nav.html
{% load static %}

<nav class="navbar navbar-expand-md bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}" style="vertical-align: center;">
      <img src="{% static 'icons/maio_32.png' %}" type="image/png" style="width: 28px; margin-top: -0.4em;">
      <span style="margin: 0.2em 0 0.2em 0.2em; display: inline-block">Maio</span>
    </a>
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if request.user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{request.user}}
          </a>
          {% if request.user.is_authenticated %}
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'dashboard' %}">Dashboard</a></li>
              <li><a class="dropdown-item" href="{% url 'upload_media' %}">Upload Media</a></li>
              <li><a class="dropdown-item" href="{% url 'library_share' %}">Library Share</a></li>

              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'edit_profile' %}">Edit Profile</a></li>

              {% if request.user.is_superuser %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'admin:index' %}">Django Admin</a></li>
              <li><a class="dropdown-item" href="{% url 'maio_admin:home' %}">Maio Admin</a></li>
              {% endif %}

              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
            </ul>
          {% endif %}
        </li>
      </ul>
      <form class="d-flex" role="search" action="{% url 'search' %}">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    {% endif %}
  </div>
</nav>